---
apiVersion: v1
kind: Namespace
metadata:
  name: flinks

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flinks-ingress
  namespace: flinks
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: challenge.domain.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flinks-nginx
            port:
              number: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: flinks
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      log_format  main
              'remote_addr:$remote_addr\t'
              'time_local:$time_local\t'
              'method:$request_method\t'
              'uri:$request_uri\t'
              'host:$host\t'
              'status:$status\t'
              'bytes_sent:$body_bytes_sent\t'
              'referer:$http_referer\t'
              'useragent:$http_user_agent\t'
              'forwardedfor:$http_x_forwarded_for\t'
              'request_time:$request_time';

      access_log    /var/log/nginx/access.log main;

      server {
          listen       80;
          return       404;
          root         /usr/share/nginx/html;
          server_name  _;

          access_log   /var/log/nginx/app.access_log main;
          error_log    /var/log/nginx/app.error_log;
      }
      include /etc/nginx/virtualhost/virtualhost.conf;
    }
  index.html: |
    <html>
    <body>
    Hello Flinks
    </body>
    </html>
  virtualhost.conf: |
    upstream app {
      server localhost:8080;
      keepalive 1024;
    }

    server {
      listen       80;
      root         /usr/share/nginx/html;
      server_name  challenge.domain.local;

      access_log   /var/log/nginx/app.access_log main;
      error_log    /var/log/nginx/app.error_log;

      location / {
        try_files $uri $uri/ =404;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flinks-nginx
  namespace: flinks
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
          - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx # mount nginx-conf volumn to /etc/nginx
              readOnly: true
              name: nginx-conf
            - mountPath: /usr/share/nginx/html
              readOnly: true
              name: nginx-index
            - mountPath: /var/log/nginx
              name: log
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: virtualhost.conf
                path: virtualhost/virtualhost.conf
        - name: nginx-index
          configMap:
            name: nginx-conf
            items:
              - key: index.html
                path: index.html
        - name: log
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: flinks-nginx
  namespace: flinks
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
